# Generated by Django 4.0.4 on 2022-05-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='BrawlMap',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='map',
            new_name='map_played',
        ),
    ]
