# Generated by Django 4.0.8 on 2022-10-13 17:01

from django.db import migrations
from datetime import datetime, timezone


def change_date(apps, schema_editor):
    Player = apps.get_model("player_lookup", "Player")
    # Due to server's very limited capacity, we can't update all players at once.
    batch_to_update = Player.objects.filter(
        default_date__gt=datetime(year=2022, month=10, day=10, tzinfo=timezone.utc)
    )[:500]
    while batch_to_update:
        batch_to_update = Player.objects.filter(
            default_date__gt=datetime(year=2022, month=10, day=10, tzinfo=timezone.utc)
        )[:500]
        player_batch = []
        for player in batch_to_update:
            player.default_date = datetime(
                year=2022, month=10, day=10, tzinfo=timezone.utc
            )
            player_batch.append(player)
        if player_batch:
            Player.objects.bulk_update(player_batch, ["default_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("player_lookup", "0002_player_default_date"),
    ]

    operations = [
        migrations.RunPython(change_date, reverse_code=migrations.RunPython.noop),
    ]
