# Generated by Django 4.0.4 on 2022-05-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0002_rename_map_brawlmap_rename_map_match_map_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_rank',
            field=models.CharField(choices=[('1', 'Bronze I'), ('2', 'Bronze II'), ('3', 'Bronze III'), ('4', 'Silver I'), ('5', 'Silver II'), ('6', 'Silver III'), ('7', 'Gold I'), ('8', 'Gold II'), ('9', 'Gold III'), ('10', 'Diamond I'), ('11', 'Diamond II'), ('12', 'Diamond III'), ('13', 'Mythic I'), ('14', 'Mythic II'), ('15', 'Mythic III'), ('16', 'Legendary I'), ('17', 'Legendary II'), ('18', 'Legendary III'), ('19', 'Masters')], default='1', max_length=20),
        ),
    ]
