# Generated by Django 4.0.4 on 2022-05-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0002_rename_has_won_matchissue_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchissue',
            name='played_with_clubmate',
            field=models.BooleanField(default=False),
        ),
    ]
