# Generated by Django 4.0.4 on 2022-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0003_alter_club_club_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_rank',
        ),
        migrations.RemoveField(
            model_name='club',
            name='club_rank_image',
        ),
        migrations.AddField(
            model_name='club',
            name='required_trophies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='trophies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
