# Generated by Django 4.0.4 on 2022-05-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0004_remove_club_club_rank_remove_club_club_rank_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='type',
            new_name='club_type',
        ),
    ]
