# Generated by Django 4.0.4 on 2022-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0004_player_brawlclub_rating_player_club_league_playrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
