# Generated by Django 4.0.4 on 2022-05-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0005_rename_type_club_club_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchissue',
            name='is_star_player',
            field=models.BooleanField(default=False),
        ),
    ]
