# Generated by Django 4.0.8 on 2022-11-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0006_player_number_of_available_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
