# Generated by Django 4.0.4 on 2022-05-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0006_matchissue_is_star_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchissue',
            name='has_won',
            field=models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('DRAW', 'Draw'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=7),
        ),
    ]
