# Generated by Django 4.0.4 on 2022-05-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0007_alter_matchissue_has_won'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['club_tag'], name='player_look_club_ta_552726_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['player_tag'], name='player_look_player__9ee822_idx'),
        ),
    ]
