# Generated by Django 4.0.4 on 2022-07-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0007_alter_player_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
