# Generated by Django 4.0.8 on 2022-11-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0007_playersupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersupdate',
            name='club_league_running',
            field=models.BooleanField(default=False),
        ),
    ]
