# Generated by Django 4.0.4 on 2022-07-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0008_player_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='duo_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='solo_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_3v3_wins',
            field=models.IntegerField(default=0),
        ),
    ]
