# Generated by Django 4.0.4 on 2022-07-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0009_player_duo_wins_player_solo_wins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy_count', models.IntegerField(default=0)),
                ('total_club_war_trophy_count', models.IntegerField(default=0)),
                ('brawlclub_rating', models.FloatField(default=0)),
                ('club_league_winrate', models.FloatField(default=0)),
                ('club_league_playrate', models.FloatField(default=0)),
                ('club_league_teamplay_rate', models.FloatField(default=0)),
                ('snapshot_date', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_lookup.player')),
            ],
        ),
    ]
