# Generated by Django 4.0.4 on 2022-10-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0010_playerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_tag',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
