# Generated by Django 4.0.4 on 2022-10-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0011_alter_player_player_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_tag',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
