# Generated by Django 4.0.4 on 2022-10-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0012_alter_club_club_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
