# Generated by Django 4.0.4 on 2022-10-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_lookup', '0013_alter_club_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
